/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_TODOLIST_TODOLIST_PB_H_INCLUDED
#define PB_TODOLIST_TODOLIST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Style guide prefers prefixing enum values instead of surrounding
 with an enclosing message */
typedef enum _todolist_TaskState { 
    todolist_TaskState_TASK_OPEN = 0, 
    todolist_TaskState_TASK_IN_PROGRESS = 1, 
    todolist_TaskState_TASK_POST_PONED = 2, 
    todolist_TaskState_TASK_CLOSED = 3, 
    todolist_TaskState_TASK_DONE = 4 
} todolist_TaskState;

/* Struct definitions */
typedef struct _todolist_TodoList { 
    int32_t owner_id;
    pb_callback_t owner_name;
    pb_callback_t todos;
} todolist_TodoList;

typedef struct _todolist_TodoList_ListItems { 
    todolist_TaskState state;
    pb_callback_t task;
    pb_callback_t due_date;
} todolist_TodoList_ListItems;


/* Helper constants for enums */
#define _todolist_TaskState_MIN todolist_TaskState_TASK_OPEN
#define _todolist_TaskState_MAX todolist_TaskState_TASK_DONE
#define _todolist_TaskState_ARRAYSIZE ((todolist_TaskState)(todolist_TaskState_TASK_DONE+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define todolist_TodoList_init_default           {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define todolist_TodoList_ListItems_init_default {_todolist_TaskState_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define todolist_TodoList_init_zero              {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define todolist_TodoList_ListItems_init_zero    {_todolist_TaskState_MIN, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define todolist_TodoList_owner_id_tag           1
#define todolist_TodoList_owner_name_tag         2
#define todolist_TodoList_todos_tag              3
#define todolist_TodoList_ListItems_state_tag    1
#define todolist_TodoList_ListItems_task_tag     2
#define todolist_TodoList_ListItems_due_date_tag 3

/* Struct field encoding specification for nanopb */
#define todolist_TodoList_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    owner_id,          1) \
X(a, CALLBACK, SINGULAR, STRING,   owner_name,        2) \
X(a, CALLBACK, REPEATED, MESSAGE,  todos,             3)
#define todolist_TodoList_CALLBACK pb_default_field_callback
#define todolist_TodoList_DEFAULT NULL
#define todolist_TodoList_todos_MSGTYPE todolist_TodoList_ListItems

#define todolist_TodoList_ListItems_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, CALLBACK, SINGULAR, STRING,   task,              2) \
X(a, CALLBACK, SINGULAR, STRING,   due_date,          3)
#define todolist_TodoList_ListItems_CALLBACK pb_default_field_callback
#define todolist_TodoList_ListItems_DEFAULT NULL

extern const pb_msgdesc_t todolist_TodoList_msg;
extern const pb_msgdesc_t todolist_TodoList_ListItems_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define todolist_TodoList_fields &todolist_TodoList_msg
#define todolist_TodoList_ListItems_fields &todolist_TodoList_ListItems_msg

/* Maximum encoded size of messages (where known) */
/* todolist_TodoList_size depends on runtime parameters */
/* todolist_TodoList_ListItems_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
