/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "todolist.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(todolist_TodoList, todolist_TodoList, AUTO)


PB_BIND(todolist_TodoList_ListItems, todolist_TodoList_ListItems, AUTO)




